---
# Install and configure application code

- name: install supervisor
  apt: name=supervisor state=present

- name: install pip
  apt: name=python-pip state=present

- name: install gunicorn
  pip: name=gunicorn

- name: install habanero
  pip: name='https://github.com/Antojitos/habanero/archive/{{ habanero_version }}.tar.gz'
  notify: restart supervisor

- name: create configuration directory
  file: path=/etc/habanero state=directory mode=0755

- name: create configuration file for supervisor
  template: src=supervisor-habanero.conf.j2 dest=/etc/supervisor/conf.d/habanero.conf
  notify: update supervisor
